cookie:
  expiry_days: 1
  key: battery@100
  name: admin
credentials:
  usernames:
    admin:
      email: admin@gmail.com
      failed_login_attempts: 0
      first_name: electica
      last_name: admin
      logged_in: true
      password: $2b$12$PTFnal.An9jERWhP5GeUjuzqVvmsoXLGSYJHk5ZBhDMFYXV.EJWQ6
      roles:
      - admin
